CREATE USER c##dbzuser IDENTIFIED BY dbz
  DEFAULT TABLESPACE LOGMINER_TBS
  QUOTA UNLIMITED ON LOGMINER_TBS;

GRANT CREATE SESSION TO c##dbzuser;
GRANT SET CONTAINER TO c##dbzuser;
GRANT SELECT ON V_$DATABASE TO c##dbzuser;
GRANT SELECT ANY DICTIONARY TO c##dbzuser;
GRANT LOCK ANY TABLE TO c##dbzuser;

GRANT SELECT ANY TABLE TO c##dbzuser;
GRANT FLASHBACK ANY TABLE TO c##dbzuser;
GRANT SELECT_CATALOG_ROLE TO c##dbzuser;
GRANT EXECUTE_CATALOG_ROLE TO c##dbzuser;
GRANT SELECT ANY TRANSACTION TO c##dbzuser;

EXIT;