CREATE TABLESPACE CUSER_TBS DATAFILE SIZE 100M AUTOEXTEND ON NEXT 100M;

CREATE USER c##dbzuser IDENTIFIED BY dbz
  DEFAULT TABLESPACE CUSER_TBS
  QUOTA UNLIMITED ON CUSER_TBS;

GRANT CREATE SESSION TO c##dbzuser;
GRANT SET CONTAINER TO c##dbzuser;
GRANT SELECT ON V_$DATABASE TO c##dbzuser;
GRANT SELECT ANY DICTIONARY TO c##dbzuser;
GRANT LOCK ANY TABLE TO c##dbzuser;

GRANT SELECT ANY TABLE TO c##dbzuser;
GRANT FLASHBACK ANY TABLE TO c##dbzuser;
GRANT SELECT_CATALOG_ROLE TO c##dbzuser;
GRANT EXECUTE_CATALOG_ROLE TO c##dbzuser;
GRANT SELECT ANY TRANSACTION TO c##dbzuser;

GRANT SELECT, FLASHBACK ON SYS.CCOL$ TO c##dbzuser;
GRANT SELECT, FLASHBACK ON SYS.CDEF$ TO c##dbzuser;
GRANT SELECT, FLASHBACK ON SYS.COL$ TO c##dbzuser;
GRANT SELECT, FLASHBACK ON SYS.DEFERRED_STG$ TO c##dbzuser;
GRANT SELECT, FLASHBACK ON SYS.ECOL$ TO c##dbzuser;
GRANT SELECT, FLASHBACK ON SYS.LOB$ TO c##dbzuser;
GRANT SELECT, FLASHBACK ON SYS.LOBCOMPPART$ TO c##dbzuser;
GRANT SELECT, FLASHBACK ON SYS.LOBFRAG$ TO c##dbzuser;
GRANT SELECT, FLASHBACK ON SYS.OBJ$ TO c##dbzuser;
GRANT SELECT, FLASHBACK ON SYS.TAB$ TO c##dbzuser;
GRANT SELECT, FLASHBACK ON SYS.TABCOMPART$ TO c##dbzuser;
GRANT SELECT, FLASHBACK ON SYS.TABPART$ TO c##dbzuser;
GRANT SELECT, FLASHBACK ON SYS.TABSUBPART$ TO c##dbzuser;
GRANT SELECT, FLASHBACK ON SYS.TS$ TO c##dbzuser;
GRANT SELECT, FLASHBACK ON SYS.USER$ TO c##dbzuser;
GRANT SELECT, FLASHBACK ON XDB.XDB$TTSET TO c##dbzuser;

DECLARE
CURSOR C1 IS SELECT TOKSUF FROM XDB.XDB$TTSET;
CMD VARCHAR2(2000);
BEGIN
FOR C IN C1 LOOP
      CMD := 'GRANT SELECT, FLASHBACK ON XDB.X$NM' || C.TOKSUF || ' TO c##dbzuser';
EXECUTE IMMEDIATE CMD;
CMD := 'GRANT SELECT, FLASHBACK ON XDB.X$QN' || C.TOKSUF || ' TO c##dbzuser';
EXECUTE IMMEDIATE CMD;
CMD := 'GRANT SELECT, FLASHBACK ON XDB.X$PT' || C.TOKSUF || ' TO c##dbzuser';
EXECUTE IMMEDIATE CMD;
END LOOP;
END;
/


CREATE TABLESPACE TBLS1 DATAFILE SIZE 100M AUTOEXTEND ON NEXT 100M;
ALTER TABLESPACE TBLS1 FORCE LOGGING;

CREATE USER USR1 IDENTIFIED BY USR1PWD
    DEFAULT TABLESPACE TBLS1
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON TBLS1;


GRANT CREATE SESSION TO USR1;
GRANT CREATE TABLE TO USR1;
GRANT CREATE SEQUENCE TO USR1;
GRANT CREATE TRIGGER TO USR1;
GRANT CREATE PROCEDURE TO USR1;
GRANT CREATE VIEW TO USR1;

CREATE TABLE USR1.ADAM1(
    ID         NUMBER NOT NULL,
    NAME       VARCHAR2(30),
    COUNT      NUMBER,
    START_TIME TIMESTAMP
);
ALTER TABLE USR1.ADAM1 ADD CONSTRAINT ADAM1PK PRIMARY KEY(ID);

ALTER TABLE USR1.ADAM1 ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

EXIT;